### ISSUE TITLE
Why hide the PKey<Private> field?

### ISSUE THREAD

**Issue by adelbertc** [durch/rust-jwt#3]
Hello again :-)

So for my app I am also using the `GOOGLE_APPLICATION_CREDENTIALS` file to generate signed URLs for GCS using the RSA key stored inside. I am currently parsing that file twice, once to get the `PKey<Private>` myself so I can sign things and once for `goauth`'s purpose. This double parse is not a huge deal with led me to do some investigating..

I noticed that inside `goauth::credentials::Credentials` the only way to get the RSA key is out is via the [`Credentials::rsa_key()`](https://docs.rs/goauth/0.8.0/src/goauth/credentials.rs.html#32-34) method which returns a `smpl_jwt::RSAKey`, which in turn [wraps an `openssl::pkey::PKey<openssl::pkey::Private>`](https://docs.rs/smpl_jwt/0.5.0/src/smpl_jwt/lib.rs.html#60-62) which is the exact type I need for my signing. However as far as I can tell there is nothing on `RSAKey` that will allow me to get the wrapped `PKey` - is this by design or is this something you would be open to a PR for (and subsequently a PR to goauth for bumping the `smpl_jwt` version?

Thanks!

**Comment by durch** [comment]
Hi @adelbertc, not a lot of design went into the `jwt` crate, please PR the change :)

**Comment by adelbertc** [comment]
Will do :-) Do you have a preference between just passing in a `PKey<Private>` around or would you like to just have a method and/or make the struct field `pub`? Or I guess the real question might be, was there a reason you chose to wrap `PKey<Private>` with `RSAKey` as opposed to just passing around the `PKey` unwrapped?

**Comment by durch** [comment]
Looking at it now, it was probably to get these [`impls`](https://github.com/durch/rust-jwt/blob/master/src/lib.rs#L64) for ergonomics. There might have been changes in the APIs so there might be a more ergonomic way of doing it. I don't have a strong preference, I'd suggest going with the smallest change, then see if an opportunity to simplify presents itself :)
